In [2]:
import numpy as np

In [3]:
#1D array
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#2D array
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
#dimensions
a.ndim


1

In [10]:
b.ndim

2

In [11]:
#shape
a.shape

(3,)

In [12]:
b.shape

(2, 3)

In [13]:
#1D array with data type
#if we insert float numbers still dtype will remian int16 
c=np.array([1,2,3],dtype='int16')
print(c)

[1 2 3]


In [14]:
#data type of c
c.dtype

dtype('int16')

In [15]:
#data type of a
a.dtype

dtype('int32')

In [17]:
#number of elements in array
a.size

3

In [18]:
b.size

6

In [19]:
#number of bytes occupied by the array
a.nbytes

12

In [20]:
b.nbytes

24

In [21]:
#less bytes as dtype is int16
c.nbytes

6