In [1]:
import numpy as np

In [2]:
a=np.full((4,5),4)
b=np.full((5,6),5)

In [3]:
#multiply both matrix
np.matmul(a,b)

array([[100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])

In [8]:
#determinant of matrix
c=np.array([[1,-2,3],[2,0,3],[1,5,4]])
np.linalg.det(c)

24.999999999999996

In [10]:
#determinant of matrix rounding to integer
c=np.array([[1,-2,3],[2,0,3],[1,5,4]])
round(np.linalg.det(c))

25

*Statistics*

In [11]:
a=np.array([[1,2,3],[4,5,6]])
np.max(a)


6

In [12]:
#column sum
np.sum(a,axis=0)

array([5, 7, 9])

In [13]:
#row sum
np.sum(a,axis=1)

array([ 6, 15])

In [14]:
#total sum
np.sum(a)

21