In [3]:
import numpy as np

In [4]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
a[0,2]

3

In [7]:
#print row
print(a[0])

[1 2 3 4 5 6 7]


In [8]:
#print column
print(a[:,0])

[1 8]


In [10]:
#change value
a[0,3]=24
print(a)

[[ 1  2  3 24  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
#change value of a particular column to same
a[:,4]=3
print(a)

[[ 1  2  3 24  3  6  7]
 [ 8  9 10 11  3 13 14]]


In [12]:
#change column value according to need
a[:,5]=(78,87)
print(a)

[[ 1  2  3 24  3 78  7]
 [ 8  9 10 11  3 87 14]]
