In [1]:
import numpy as np

In [2]:
#print row of zeros
np.zeros(4)

array([0., 0., 0., 0.])

In [3]:
#argumnets taken (shape,dtype,order="C")
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
#argumnets taken (shape,dtype,order="C")
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
#argumnets taken (shape,fill value,dtype)
#fill value is the value which is present in n*m matrix made
np.full((4,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [7]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
#full_like will make an array of same dimensions as passed 1st argument will fill value as second argument
#arguments taken (array_name,fill_value,dtype)
np.full_like(a,7)

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [8]:
#random matrix
np.random.rand(4,2)

array([[0.12199022, 0.74154013],
       [0.01731188, 0.63559007],
       [0.39629223, 0.10204998],
       [0.8284061 , 0.199225  ]])

In [10]:
#random matrix of given shape
np.random.random_sample(a.shape)

array([[0.38188818, 0.92666438, 0.34659172, 0.57112014, 0.77132839,
        0.16643268, 0.63193542],
       [0.84262507, 0.35547565, 0.10505204, 0.92087882, 0.61470988,
        0.80117418, 0.52118781]])

In [11]:
#identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [20]:
#stacking matrix/repeating
a=np.array([[1,2,3]])
#vertical repeat
a1=np.repeat(a,3,axis=0)
#horizontal repeat
a2=np.repeat(a,3,axis=1)
print(a1,"\n",a2)

[[1 2 3]
 [1 2 3]
 [1 2 3]] 
 [[1 1 1 2 2 2 3 3 3]]
