In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3,4],[5,6,7,8]])

In [5]:
#reshape array
b=a.reshape((4,2))
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

In [9]:
#vertical stacking
v=np.vstack([v1,v2])
print(v)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
#horizontal stacking
v=np.hstack([v1,v2])
print(v)

[1 2 3 4 5 6 7 8]
